Att

diff --git a/bin/pushit b/bin/pushit
--- a/bin/pushit
+++ b/bin/pushit
@@ -59,10 +59,11 @@ redmine_time_entry() {
 	hours=$2
 
 	if [ "$number" == "" ] || [ "$hours" == "" ]; then
-		echo "issue_id (required)\nhours (required)\n"
-	else
-		curl -v -H "Content-Type: application/json" -X POST -d "<time_entry><issue_id>$number</issue_id><hours>$hours</hours></time_entry>" -H "X-Redmine-API-Key: $token" http://suporte.cers.com.br/time_entries.xml
+		printf "issue_id (required)\nhours (required)\n\n"
+		exit 1;
 	fi;
+
+	curl -v -H "Content-Type: application/xml" -X POST -d "<time_entry><issue_id>$number</issue_id><hours>$hours</hours><activity_id>16</activity_id></time_entry>" -H "X-Redmine-API-Key: $token" http://suporte.cers.com.br/time_entries.xml
 }
 
 # ==============================
@@ -160,7 +161,7 @@ help() {
 }
 
 version() {
-	printf 'version: 2.3.2\n'
+	printf 'version: 2.3.3\n'
 
 	printf '\n -------------------------\n'
 	printf ' OS NAME: '
