CR: #123123 | Alteracoes feitas no codigo do Pushit

diff --git a/pushit b/pushit
--- a/pushit
+++ b/pushit
@@ -32,27 +32,20 @@ init_redmine() {
 redmine() {
 	token=$( get_redmine_token )
 	number=$1
-	status=2
-	if [ "$2" != "" ]; then
-		status=32
-	fi
-	curl -v -H "Content-Type: application/json" -X PUT -d "{ \"issue\": { \"id\": \"$number\", \"status_id\": \"$status\" } }" -H "X-Redmine-API-Key: $token" http://suporte.cers.com.br/issues/$number.json
+	curl -v -H "Content-Type: application/json" -X PUT -d "{ \"issue\": { \"id\": \"$number\", \"status_id\": \"32\" } }" -H "X-Redmine-API-Key: $token" http://suporte.cers.com.br/issues/$number.json
 }
 
 pushit() {
-	# Get branch
 	branch=$3
 	if [ "$branch" == "" ]; then
 		branch="$(git branch | grep '* ' | sed -e 's/* //g')"
 	fi
 
-	# Check parameters
 	if [ "$1" == "" ] && [ "$2" == "" ]; then
 		printf 'Please, enter the CR number with the option -n, or describe it using the option -m\n\n'
 		exit 1;
 	fi
 
-	# Commit message
 	message="CR: #$1 | $2"
 	if [ "$1" == "" ]; then
 		message="$2"
@@ -77,7 +70,6 @@ pushit() {
 	fi
 
 	printf "\nFatality...\n"
-	exit 1;
 }
 
 setup() {
@@ -90,6 +82,7 @@ setup() {
 
 	if [ "$hasMessage" != 'Y' ] && [ "$hasMessage" != 'y' ]; then
 		pushit "$number"
+		exit 1;
 	fi
 
 	read -p "Commit message: " message
@@ -123,64 +116,51 @@ version() {
 	printf 'version: 2.1.0\n'
 }
 
-init_flags() {
-	if [ "$1" == "" ]; then
+main() {
+	init_redmine
+
+	if [ $# -eq 0 ]; then
 		setup
-	elif [ "$1" == '-h' -o "$1" == 'help' ]; then
+	elif [ $1 == '-h' -o $1 == 'help' ]; then
 		help
-		exit 1;
-	elif [ "$1" == '-v' -o "$1" == 'version' ]; then
+	elif [ $1 == '-v' -o $1 == 'version' ]; then
 		version
-		exit 1;
-	elif [ "$1" == '-r' -o "$1" == 'redmine' ]; then
+	elif [ $1 == '-r' -o $1 == 'redmine' ]; then
 		config_redmine
-		exit 1;
-	elif [ "$1" == '-p' -o "$1" == 'pull' ]; then
+	elif [ $1 == '-p' -o $1 == 'pull' ]; then
 		branch="$(git branch | grep '* ' | sed -e 's/* //g')"
 		git pull origin $branch
-		exit 1;
-	elif [ "$1" == '-s' -o "$1" == 'status' ]; then
+	elif [ $1 == '-s' -o $1 == 'status' ]; then
 		git status
-		exit 1;
+	else
+		message=''
+		number=''
+		branch=''
+		while getopts ":m:b:n:r:" arg; do
+			case $arg in
+				m)
+					message="$OPTARG"
+					;;
+				b)
+					branch=$OPTARG
+					;;
+				n)
+					number=$OPTARG
+					;;
+				r)
+					redmine="$OPTARG"
+					config_redmine $redmine
+					exit 1;
+					;;
+				*)
+					printf "Invalid option. Use -h option to open the help text.\n"
+					exit 1;
+					;;
+			esac
+		done
+
+		pushit "$number" "$message" "$branch"
 	fi
-}
-
-init_options() {
-	message=''
-	number=''
-	branch=''
-	close_message=''
-	while getopts ":m:b:n:c:" arg; do
-		case $arg in
-			m)
-				message="$OPTARG"
-				;;
-			b)
-				branch=$OPTARG
-				git checkout $branch
-				exit 1;
-				;;
-			n)
-				number=$OPTARG
-				;;
-			c)
-				close_message=$OPTARG
-				;;
-			*)
-				printf "Invalid option. Use -h option to open the help text.\n"
-				exit 1;
-				;;
-		esac
-	done
-
-	pushit "$number" "$message" "$branch" "$close_message"
-}
-
-main() {
-
-	init_redmine
-	init_flags "$1"
-	init_options "$@"
 
 	exit 1;
 }
